import Head from 'next/head';
import Image from 'next/image';

export default function Home() {
  return (
    <div className="w-full">
      <Head>
        <title>Marsleaders</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="h-100-vh w-full flex relative">
        <div className="min-w-6-0 w-6-0 h-full absolute bg-black"></div>
        <div className="">
          <img className="h-full" src="/cover-image.png" alt="" />
        </div>
      </section>
      <section className="h-100-vh w-full flex relative">
        <div className="min-w-6-0 w-6-0 h-full absolute bg-red-darker"></div>
        <div className="">2</div>
      </section>
      <section className="h-100-vh w-full flex relative">
        <div className="min-w-6-0 w-6-0 h-full absolute bg-red-darker"></div>
        <div>3</div>
      </section>
      <section className="h-100-vh w-full flex relative">
        <div className="min-w-6-0 w-6-0 h-full absolute bg-text-primary"></div>
        <div>4</div>
      </section>
    </div>
  );
}
